# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IceTeaMessage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IceTeaMessage
  pod 'Firebase/Core'
#  pod 'FirebaseUI'
  pod 'SVProgressHUD'
  pod "BSImagePicker", "~> 2.8"
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'SwiftyUserDefaults', :git => "https://github.com/radex/SwiftyUserDefaults.git"
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'AlamofireImage', '~> 3.5'
end
